### ISSUE TITLE
POC - Home Page and Events

### ISSUE THREAD

**Issue by EricRobertCampbell** [EricRobertCampbell/alberta-paleontological-society-website#4]
- [ ] Make a full POC (including styling, contents, and mobile-friendliness) for the home page and the events page.
- [ ] Solicit comments: Edi and maybe Amy?
- [ ] Send to Vaclav

**Comment by EricRobertCampbell** [comment]
# Roadmap

- [ ] Events should populate from a content collection
- [ ] Events should sort automatically
- [ ] JS: on load, filter the events into Today, Upcoming, and Past
- [ ] Frontpage: query the events and display any event that is today.
- [ ] Add in some of the actual events
- [ ] Ensure that everything is mobile-friendly
- [ ] Come up with three different styles - look to other sites for inspiration about the layout, &c.
